"""
Default skill categories and skills for the SkillSwap platform.
Used for seeding the database.
"""

DEFAULT_CATEGORIES: list[dict[str, str]] = [
    {
        "name": "Technology",
        "icon": "laptop",
        "description": "Programming, web development, data science, and all things tech.",
    },
    {
        "name": "Languages",
        "icon": "globe",
        "description": "Foreign languages, sign language, and communication skills.",
    },
    {
        "name": "Music",
        "icon": "music",
        "description": "Instruments, music theory, production, and vocal training.",
    },
    {
        "name": "Art & Design",
        "icon": "palette",
        "description": "Drawing, painting, graphic design, photography, and visual arts.",
    },
    {
        "name": "Cooking",
        "icon": "utensils",
        "description": "Culinary skills, baking, cuisines from around the world.",
    },
    {
        "name": "Sports & Fitness",
        "icon": "dumbbell",
        "description": "Athletics, yoga, martial arts, and personal fitness.",
    },
    {
        "name": "Business",
        "icon": "briefcase",
        "description": "Entrepreneurship, marketing, finance, and professional skills.",
    },
    {
        "name": "Academic",
        "icon": "graduation-cap",
        "description": "Mathematics, science, writing, and academic tutoring.",
    },
    {
        "name": "Crafts & DIY",
        "icon": "scissors",
        "description": "Woodworking, knitting, electronics, and hands-on projects.",
    },
    {
        "name": "Wellness",
        "icon": "heart",
        "description": "Meditation, nutrition, mental health, and holistic well-being.",
    },
]

DEFAULT_SKILLS: dict[str, list[str]] = {
    "Technology": [
        "Python",
        "JavaScript",
        "TypeScript",
        "React",
        "Node.js",
        "SQL",
        "Machine Learning",
        "DevOps",
        "Mobile Development",
        "Cybersecurity",
    ],
    "Languages": [
        "English",
        "Spanish",
        "French",
        "Mandarin",
        "Japanese",
        "German",
        "Portuguese",
        "Korean",
        "Arabic",
        "Sign Language",
    ],
    "Music": [
        "Guitar",
        "Piano",
        "Drums",
        "Violin",
        "Singing",
        "Music Theory",
        "Music Production",
        "DJ Skills",
        "Songwriting",
        "Bass Guitar",
    ],
    "Art & Design": [
        "Drawing",
        "Painting",
        "Graphic Design",
        "Photography",
        "UI/UX Design",
        "3D Modeling",
        "Animation",
        "Calligraphy",
        "Watercolor",
        "Digital Illustration",
    ],
    "Cooking": [
        "Baking",
        "Italian Cuisine",
        "Japanese Cuisine",
        "Pastry Making",
        "Vegan Cooking",
        "BBQ & Grilling",
        "Indian Cuisine",
        "Meal Prep",
        "Fermentation",
        "Cocktail Making",
    ],
    "Sports & Fitness": [
        "Yoga",
        "Weight Training",
        "Swimming",
        "Martial Arts",
        "Running",
        "Rock Climbing",
        "Tennis",
        "Basketball",
        "Cycling",
        "Dance",
    ],
    "Business": [
        "Marketing",
        "Finance",
        "Public Speaking",
        "Project Management",
        "Entrepreneurship",
        "Negotiation",
        "Sales",
        "Accounting",
        "Leadership",
        "Stock Trading",
    ],
    "Academic": [
        "Mathematics",
        "Physics",
        "Chemistry",
        "Biology",
        "Creative Writing",
        "Essay Writing",
        "Statistics",
        "History",
        "Philosophy",
        "Research Methods",
    ],
    "Crafts & DIY": [
        "Woodworking",
        "Knitting",
        "Sewing",
        "Electronics",
        "Pottery",
        "Jewelry Making",
        "Leatherworking",
        "3D Printing",
        "Home Repair",
        "Gardening",
    ],
    "Wellness": [
        "Meditation",
        "Nutrition",
        "Life Coaching",
        "Stress Management",
        "Aromatherapy",
        "First Aid",
        "Massage Techniques",
        "Mindfulness",
        "Sleep Optimization",
        "Breathwork",
    ],
}
